# ------------------------------------------------------------------------------
# WolvesOnMeds plugin configuration
# ------------------------------------------------------------------------------
heal:
  max-health: 100
  min-health: 0
  duration: 60
  delay: 10
debug: false
