author: Elusive92
database: false
description: Heals tamed wolves over time.
website: http://forums.bukkit.org/threads/28591/
main: net.elusive92.bukkit.wolvesonmeds.WolvesOnMeds
name: WolvesOnMeds
startup: postworld

# Note to self: Remember to update the version in pom.xml, too!
version: '1.4'

permissions:
  wolvesonmeds.heal:
    description: Whether the players wolves regain health.
    default: true
  wolvesonmeds.no-delay:
    description: Whether the players wolves bypass the healing delay.
    default: false
