author: Elusive92
database: false
description: Heals tamed wolves over time.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.elusive92.bukkit.wolvesonmeds.WolvesOnMeds
name: WolvesOnMeds
startup: postworld

# Note to self: Remember to update the version in pom.xml, too!
version: '1.0'
